services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: Admin@123
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: smtp.gmail.com:587
      GF_SMTP_USER: hariharananalyst@gmail.com
      GF_SMTP_PASSWORD: mmdsvygacpchpzkw
      GF_SMTP_FROM_ADDRESS: hariharananalyst@gmail.com
      GF_SMTP_FROM_NAME: Grafana
    depends_on:
      - prometheus
      - node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"

volumes:
  grafana-data: