pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ai-cicd-app -f docker/Dockerfile .'
            }
        }

        stage('Stop Old Container') {
            steps {
                sh 'docker stop ai-cicd-container || true'
                sh 'docker rm ai-cicd-container || true'
            }
        }

        stage('Run New Container') {
            steps {
                sh 'docker run -d --restart unless-stopped -p 8081:80 --name ai-cicd-container ai-cicd-app'
            }
        }

        stage('Deploy Monitoring') {
            steps {
                dir('monitoring') {
                    sh 'docker compose down'
                    sh 'docker compose up -d'
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful!'
        }

        failure {
            echo 'Deployment Failed!'
        }
    }
}